<script setup>
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'
import SiteHeader from '../components/SiteHeader.vue'
const router=useRouter(), items=ref([]), file=ref(), title=ref(''), q=ref(''), hits=ref([]), message=ref('')
const load=async()=>items.value=(await(await fetch('/api/knowledge')).json()).items||[]; onMounted(load)
const upload=async()=>{if(!file.value)return;const f=new FormData();f.append('file',file.value);f.append('title',title.value);await fetch('/api/knowledge',{method:'POST',body:f});message.value='已上传并加入知识检索';file.value=null;title.value='';await load()}
const search=async()=>hits.value=(await(await fetch(`/api/knowledge/search?q=${encodeURIComponent(q.value)}`)).json()).results||[]
const remove=async(id)=>{await fetch(`/api/knowledge/${id}`,{method:'DELETE'});await load()}
</script>
<template><div class="page"><SiteHeader /><main><h1>知识库</h1><p>上传私有资料，聊天时按问题召回相关片段，不会把整份文档无差别塞给模型。</p><div v-if="message" class="notice">{{message}}</div><section class="upload"><input v-model="title" placeholder="知识标题（可选）"><input type="file" @change="file=$event.target.files[0]"><button @click="upload" :disabled="!file">上传并记忆</button></section><section class="search"><h2>测试知识召回</h2><div><input v-model="q" @keyup.enter="search" placeholder="输入一个真实问题"><button @click="search">检索</button></div><article v-for="h in hits" :key="h.knowledgeId+'-'+h.chunkIndex"><b>{{h.title}} · 片段 {{h.chunkIndex+1}}</b><small>相关度 {{Math.round(h.score*100)}}%</small><p>{{h.text}}</p></article></section><h2>我的知识（{{items.length}}）</h2><div class="cards"><article v-for="i in items" :key="i.id"><b>{{i.title}}</b><small>{{i.filename}}</small><p>{{i.text.slice(0,180)}}</p><button @click="remove(i.id)">删除</button></article></div></main></div></template>
<style scoped>.page{min-height:100vh;background:#f6f7fb;color:#172033}header{height:64px;padding:0 5vw;display:flex;align-items:center;justify-content:space-between;background:white;border-bottom:1px solid #e8eaf0}button{cursor:pointer}header button{border:0;background:none}header>button{font-size:19px;font-weight:800}nav{display:flex;gap:28px}main{max-width:1000px;margin:auto;padding:48px 24px}h1{font-size:42px;margin-bottom:8px}main>p{color:#687086}.notice{margin:16px 0;color:#168447}.upload,.search{background:white;border:1px solid #e4e7ee;border-radius:16px;padding:22px;margin:28px 0}.upload{display:flex;gap:10px;align-items:center}input{padding:11px 13px;border:1px solid #dfe2ea;border-radius:9px}.upload input:first-child,.search input{flex:1}.upload button,.search button{padding:11px 18px;background:#5360df;color:white;border:0;border-radius:9px}.search>div{display:flex;gap:10px}.search article,.cards article{margin-top:12px;padding:16px;background:#f8f9fc;border-radius:12px}.search small,.cards small{margin-left:10px;color:#8490a4}.search p,.cards p{color:#5d6679;line-height:1.6;white-space:pre-wrap}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.cards article{background:white;border:1px solid #e4e7ee}.cards button{color:#c43d4b;border:0;background:none}@media(max-width:700px){.upload{align-items:stretch;flex-direction:column}.cards{grid-template-columns:1fr}}</style>
